server:
  port: 8080
  servlet:
    context-path: /bayzat

spring:
  main:
    banner-mode: off
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/coindb

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true


logging:
  root: info